#!/usr/bin/env python3
"""Download the OurAirports database and build data/airports.js.

Usage: python3 scripts/build_airports.py [path/to/airports.csv]

Without an argument the CSV is downloaded from the OurAirports data mirror.
The output is a compact JS file that sets `globalThis.AIRPORTS` to a map of
ICAO code -> [name, municipality, iso_country, lat, lon, scheduled], so the app works
when index.html is opened straight from disk (no fetch / CORS needed).
"""
import csv
import io
import json
import re
import sys
import urllib.request
from pathlib import Path

SOURCE_URL = "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/airports.csv"
TYPES = {"large_airport", "medium_airport", "small_airport", "seaplane_base"}
ICAO_RE = re.compile(r"^[A-Z]{4}$")
OUT = Path(__file__).resolve().parent.parent / "data" / "airports.js"


def load_csv(argv):
    if len(argv) > 1:
        return Path(argv[1]).read_text(encoding="utf-8")
    with urllib.request.urlopen(SOURCE_URL) as resp:
        return resp.read().decode("utf-8")


def main(argv):
    rows = csv.DictReader(io.StringIO(load_csv(argv)))
    airports = {}
    rank = {"large_airport": 0, "medium_airport": 1, "small_airport": 2, "seaplane_base": 3}
    for row in rows:
        if row["type"] not in TYPES:
            continue
        code = (row["icao_code"] or row["gps_code"] or "").strip().upper()
        if not ICAO_RE.match(code):
            continue
        entry = (
            rank[row["type"]],
            [
                row["name"].strip(),
                row["municipality"].strip(),
                row["iso_country"].strip(),
                round(float(row["latitude_deg"]), 4),
                round(float(row["longitude_deg"]), 4),
                1 if row["scheduled_service"] == "yes" else 0,
            ],
        )
        # If two records claim the same code, keep the more significant airport.
        if code not in airports or entry[0] < airports[code][0]:
            airports[code] = entry

    data = {code: airports[code][1] for code in sorted(airports)}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_airports.py from OurAirports (public domain).\n"
        "// Format: ICAO -> [name, city, country, lat, lon, scheduledService]\n"
        "globalThis.AIRPORTS = "
        + json.dumps(data, ensure_ascii=False, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(data)} airports to {OUT}")


if __name__ == "__main__":
    main(sys.argv)
